version: "3"
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: cartao
      POSTGRES_PASSWORD: cartao
      POSTGRES_DB: cartao
    ports:
      - "5433:5432"
    networks:
      - store
    restart: unless-stopped

  api:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres:5432/cartao
      DATABASE_USERNAME: cartao
      DATABASE_PASSWORD: cartao
    ports:
      - "8080:8080"
    networks:
      - store
    restart: unless-stopped

networks:
  store:
    driver: bridge
